### ISSUE TITLE
A bunch of land ice failing tests in Albany

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#1077]
A bunch of tests are failing:

https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=218512

In looking at the errors, it seems at least some of them are due to changes in Albany (```Cubature Degrees (Horiz Vert)``` an unknown parameter), but some may be due to changes to Trilinos.  Could someone please have a look at these?

**Comment by bartgol** [comment]
Still working on this.

**Comment by ikalash** [comment]
A bunch more stuff got broken today in terms of the builds.  You probably know already @bartgol but letting you know just in case.

**Comment by bartgol** [comment]
This kind of build errors is unrelated to my recent changes. Perhaps STK finally removed deprecated code for fields?

https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=227393

**Comment by ikalash** [comment]
@alanw0 : we are getting STK-related errors in Albany: 

https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=227393

```
 struct FieldRank<stk::mesh::Field<Scalar,Tag1,Tag2,Tag3,Tag4,Tag5,Tag6,Tag7>> {
```
Have STK removed some more deprecated code?

**Comment by alanw0** [comment]
Sorry about that, let me bring @djglaze into this.
I think the belief was that this (final?) removal of deprecated code should have no impact since it had already been deprecated...
Dave will know more details, and can suggest the best action here...

**Comment by djglaze** [comment]
You're right that this is due to another round of deprecated code removal.  The timeline is a bit complex, so here's a quick summary:

- **3/2023**: Albany/LCM team was contacted about the "simple fields" STK changes to migrate to pure run-time sizing of `stk::mesh::Field`s.  Your team volunteered to make the changes yourselves after I struggled for a while.
- **1/2024**: All "legacy" `stk::mesh::Field` APIs were marked as deprecated, but left in place
- **7/2024**: Removed all public-facing deprecated code so that the new "simple fields" workflow is the only one supported, after (we believed) all users had been converted for more than a year
- **9/2024**: Removed all internal, inaccessible code that supported the legacy behavior

I think you're caught in the **9/2024** changes, which included things like removing the extra template parameters from the `stk::mesh::Field` type that became completely inaccessible with the **7/2024** changes.  You should be able to change:

```c++
struct FieldRank<stk::mesh::Field<Scalar,Tag1,Tag2,Tag3,Tag4,Tag5,Tag6,Tag7>> {
```

into

```c++
struct FieldRank<stk::mesh::Field<Scalar>> {
```

to get building again.  The extra tags were no longer used and no longer user-settable, so they were removed.  Sorry about all the churn.  This rollout strategy was the least-painful way we could think of to incrementally make this kind of change to STK mesh.

**Comment by bartgol** [comment]
I fixed the field error in Albany, but I'm getting linking errors due to [this](https://github.com/trilinos/Trilinos/issues/13481) STK problem. I fixed it locally in my repo, so that I can verify tests run correctly.

**Comment by bartgol** [comment]
Commit 5d400c176 fixed all tests currently failing on my workstation. We can keep the issue open, and close it on Monday if we see tests passing on cdash.

Thanks for your patience while I track these down!
