### ISSUE TITLE
DAG-related error

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#775]
I thought we had an issue on this already but I'm not finding it.  There is a DAG-related error in the FO_Hydrology_Steady_Dome_Tpetra tests:

https://sems-cdash-son.sandia.gov/cdash/test/2020364

```
p=2: *** Caught standard std::exception of type 'PHX::missing_evaluator_exception' :

 /projects/albany/nightlyAlbanyCDash/test/TrilinosInstall/include/Phalanx_DAG_Manager_Def.hpp:312:
 
 Throw number = 1
 
 Throw test that evaluated to true: node_index_it == field_to_node_index_.end()
 
 ******************************************************
 PHX::DagManager
 Evaluation Type = <Jacobian>
 ******************************************************
 
 ** Starting Required Field List
 Tag: Scatter Velocity Residual, Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::DynamicStorage<double, double> >, DataLayout: <>(0)
 Tag: Scatter Hydrology, Sacado::Fad::Exp::GeneralFad<Sacado::Fad::Exp::DynamicStorage<double, double> >, DataLayout: <>(0)
 ** Finished Required Field List
 ```

I think we had said at our meeting yesterday that @bartgol would look into this.

**Comment by bartgol** [comment]
Yes, I was able to reproduce the fail, with ENABLE_MESH_DEPENDS_ON_SOLUTION=ON (as in the cdash build).

**Comment by ikalash** [comment]
@bartgol : great!

**Comment by bartgol** [comment]
@ikalash After discussing with Mauro, I turned off the FO_Hydro tests if either one of ENABLE_MESH_DEPENDS_ON_BLAH is ON.

It turned out that fixing the test with those configs required a cascade of changes to our evaluators. Nothing "huge", but somewhat annoying, and increasing compilation times. Since those options are used mainly with thickness as an unknown or a parameter, and since we currently don't couple hydrology with thickness, I decided to leave as is (disabling the test).

If/when we get both hydrology and thickness physics coupled together, we can revisit, and fix the problematic evaluators.
