### ISSUE TITLE
Failing clang builds

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#788]
The clang builds on CEE are failing due to some template issue:

```
[ 67%] Building CXX object src/CMakeFiles/albanyPDEs.dir/evaluators/pde/PHAL_CahnHillWResid.cpp.o
/projects/albany/nightlyAlbanyCDash/repos/Albany/src/problems/Albany_ThermalProblem.cpp:31:106: error: use 'template' keyword to treat 'at' as a dependent template name
    p_->set<Teuchos::RCP<Albany::ScalarParameterAccessors<EvalT>>>("Accessors", problem_.getAccessors()->at<EvalT>());

               ^

               template
```
https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=29020
Is this due to recent Albany changes, or Trilinos, does anyone know?

**Comment by kliegeois** [comment]
I am pretty sure that it is related to my last PR.

**Comment by ikalash** [comment]
Thanks @kliegeois .  Would you mind having a look and trying to fix it when you get the chance?

**Comment by kliegeois** [comment]
Yes, I will look into that early next week.

**Comment by kliegeois** [comment]
@ikalash I think that I have fixed it except that I did not try it with clang yet.
I do not have a clang build of Trilinos and Albany available yet; it will take me a couple of hours to have them (mostly compilation time).
I can either push the fix (which works with Intel compilers and gcc) today so that the failing build is potentially gone tonight but without testing clang before pushing the fix or wait for tomorrow to have tested the fix with clang.

**Comment by bartgol** [comment]
Imho, you can push the fix, and we can wait till tomorrow. So long as intel/gcc are working, we can wait a day and check the nightlies.

**Comment by mperego** [comment]
yeah, @ikalash no need to test with clang. we'll know tomorrow.

**Comment by ikalash** [comment]
Ok fair enough.

**Comment by kliegeois** [comment]
Yes, let's just wait for tomorrow results; thanks though!
