### ISSUE TITLE
Failing nightlies due to STK changes

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#814]
Looks like we're getting failed Albany builds due to STK: https://my.cdash.org/viewBuildError.php?buildid=2181971 .  

```
[Albany/src/disc/stk/Albany_IossSTKMeshStruct.cpp:106](https://github.com/gahansen/Albany/blob/master/Albany/src/disc/stk/Albany_IossSTKMeshStruct.cpp#L106):25: error: 'class stk::io::StkMeshIoBroker' has no member named 'meta_data_rcp'; did you mean 'meta_data_ptr'?
```
Is this due to changes in STK / removal of deprecations, which were discussed by email a few weeks ago?  Tagging @alanw0 .

**Comment by alanw0** [comment]
@ikalash Hi Irina! Yes this method was deprecated. There is now a similar method called 'meta_data_ptr' which you can use instead, however it returns std::shared_ptr instead of Teuchos::RCP.
In stk our procedure is to delete deprecated methods after they have been marked deprecated for approx 6 weeks.

**Comment by ikalash** [comment]
It looks like there is still a problem in one of the builds:

https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=35604

``
/.../repos/Albany/src/disc/stk/Albany_STKDiscretization.cpp(2312): error: no instance of overloaded function "stk::io::StkMeshIoBroker::set_bulk_data" matches the argument list
``

**Comment by mperego** [comment]
@ikalash, it seems it's building an older version of Albany (c08885d7cd76cdbbb0016d62bfd411df3e81c2a1).
