### ISSUE TITLE
Rework nightly test names to get compiler and CUDA version by default and have consistent naming convention

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#839]
To start with, the names will have the following:

- compiler name (obtained on the fly)
- CUDA compiler name (obtained on the fly) - for CUDA build only
- Kokkos node name (hard-coded)
- whether build is debug or release (hard-coded)
- Fad type / length (hard-coded)

In the future, may want to add options like whether mesh depends on params, etc.

**Comment by bartgol** [comment]
By "CUDA compiler name" you mean the cuda version I guess? So the build name would look something like `gcc9-cuda10-cuda-debug-dfad`? I think the kokkos node name would be a bit redundant for cuda builds (and probably for HIP builds too, once we get them). I think we could assume that
- if `cudaX` or `hipY` is present, then the kokkos node is cuda or HIP respectively
- if no cuda/hip string is present, then assume kokkos serial, unless we add `-omp`. E.g.: `gcc9-debug-dfad` uses Kokkos::Serial, but `gcc9-omp-debug-dfad` uses Kokkos::OpenMP.

**Comment by ikalash** [comment]
I haven't decided yet.  It depends on what cuda info I can get from cmake.

Also worth including is the OS (e.g., rhel7 vs. rhel8).

**Comment by bartgol** [comment]
Imho, we don't need to include the Linux distro. Win vs Apple vs Linux is important, but linux distros not so much. And we're not trying to support Apple or Win builds, I assume.

**Comment by ikalash** [comment]
How about something like this for the initial version of names?  The name has the type of OS, the compiler, whether there is a release/debug build and what KokkosNode is used.  I will add the cuda version for cuda builds.  We can add the sfad stuff for cases where a non-default (DFad) fad type is used.  

https://sems-cdash-son.sandia.gov/cdash/index.php?project=Albany&date=2022-10-28&filtercount=2&showfilters=1&filtercombine=or&field1=buildname&compare1=63&value1=Linux-4.18.0-372.19.1.el8_6.x86_64-gcc-11.1.0-Release-Albany&field2=buildname&compare2=63&value2=Linux-4.18.0-372.19.1.el8_6.x86_64-gcc-11.1.0-Debug 

The os info and compiler names are autogenerated based on the environment.  Other details like the KokkosNode are hard-coded.

**Comment by bartgol** [comment]
Imho the OS name is not that important (we're always on Linux anyways), and it is kind of long. Also `Albany` in the name seems a bit redundant. I would keep names short, and add optional build specs at the end (so that the first N are _always_ the same). Something like `${compiler_id_and_version}_${deb_or_release}_${kokkos_node}`, and any additional specifier after that. So I would vote for
```
gcc11_Debug_Serial_FPE
gcc11_Release_OpenMP
gcc11_Release_Serial_NoEpetra
gcc11_Release_Serial
```
I'm voting for names "as short as possible", in view of potential proliferation of options. Right now, we have FPE, NoEpetra, FadType, MeshDependOnParams (which is already a lot if we want to add them all), but we might have more as omega_h, adaptivity, and time advance are integrated in ALI.

One thing that is not super clear to me is what compiler ID/version we should use for Cuda/HIP builds. I guess the most complete ID should include a token for the host compiler and a token for the device compiler, like `gnu9-cuda11`?

**Comment by ikalash** [comment]
Thanks for the input, Luca.  I kind of like knowing what OS is being run on the machine, but I could cut it.  I would like to include the full version of the compiler not just the integer b/c I think it is useful and b/c it is actually easier for me to do it this (the way I extract the compiler version gives the whole version).

**Comment by ikalash** [comment]
Also, we need to have either Albany or Trilinos in the name, to distinguish the builds.

**Comment by bartgol** [comment]
Full compiler version is fine. I think Albany and Trilinos entries should end in separate tabs of the cdash ([e3sm](https://my.cdash.org/index.php?project=E3SM) does that).

If you really want to put info on the OS, I would prob ask to cut some info. I don't think the Linux kernel version is _that_ important (we don't deal with such low level details in our code). Perhaps the architecture, and OS version only, like `rhel8.x86_64`?

**Comment by mperego** [comment]
I vote for adding the OS version only, like `rhel8.x86_64`.

**Comment by bartgol** [comment]
It's hard to get `rhel8` using bash commands. The best you can do is `lsb_release -rsi` which returns `RedHatEnterprise 8.6`, and then replace spaces with dots. `uname -r` returns the kernels version, which _does_ include `el8_6.x86_64` at the end, but I'm not sure how portable it is to use it do detect distro name. E.g., on rhel8 I get 
```
$ uname -r
4.18.0-372.13.1.el8_6.x86_64
```
but on my personal ArchLinux desktop I get
```
$ uname -r
5.19.9-arch1-1
```

**Comment by ikalash** [comment]
@bartgol , you hit the nail on the head - a lot of these things are hard to get.  I could probably have it put "el8_6.x86_64" with relative ease, from which you can infer the RHEL version.  

As a separate note, there is one non-ideal thing that I am doing now but that I cannot figure out how to circumvent, namely I have to pass the path to the mpicc to a function I wrote to get the information (rather than just inferring from the build what mpicc is used).  This is because the build name gets created before the cmake configure options are read.  I don't really view this as that big of a deal, as one can always just make the path to the mpicc a variable that gets set before starting the build, in which case if it gets updated in the build, it will get updated in the machine name too.

**Comment by bartgol** [comment]
> As a separate note, there is one non-ideal thing that I am doing now but that I cannot figure out how to circumvent, namely I have to pass the path to the mpicc to a function I wrote to get the information (rather than just inferring from the build what mpicc is used). This is because the build name gets created before the cmake configure options are read. I don't really view this as that big of a deal, as one can always just make the path to the mpicc a variable that gets set before starting the build, in which case if it gets updated in the build, it will get updated in the machine name too.

I'm looking at [this](https://github.com/sandialabs/Albany/blob/master/doc/dashboards/camobap.ca.sandia.gov/ctest_nightly_albany.cmake) script assuming that's roughly what you are using (if not the exact same script). Since you have access to `TRILINSTALLDIR`, perhaps you can cat the file `${TRILINSTALLDIR}/lib/cmake/Trilinos/TrilinosConfig.cmake` and grep for `Trilinos_CXX_COMPILER`.

**Comment by ikalash** [comment]
@bartgol : this would be for the Albany build.  We couldn't do it for the Trilinos build, however, which would be the first one to get posted to CDash in most cases.

**Comment by bartgol** [comment]
Ah, I see. Can you point me to the ctest cmake script as well as the bash script used to invoke it?

**Comment by ikalash** [comment]
What do you mean by 'ctest cmake script as well as bash script used to invoke it'?  Are you talking about new stuff I'm working on for how to extract the compiler name, OS, etc.?

**Comment by bartgol** [comment]
By "ctest cmake script" I mean a script like the one I linked earlier, but for trilinos. But then, that script needs to be invoked from a bash script, with a line that looks something like `ctest -S /path/to/ctestscript.cmake -DCMAKE_COMMAND="<cmake-options>"`. I just wanted to see how we invoke ctest, and the script we feed to it.

**Comment by ikalash** [comment]
Here is one of the cmake files I updated: https://github.com/sandialabs/Albany/blob/master/doc/dashboards/camobap.ca.sandia.gov/ctest_nightly_albany.cmake .  See in particular:  https://github.com/sandialabs/Albany/blob/master/doc/dashboards/camobap.ca.sandia.gov/ctest_nightly_albany.cmake#L56-L89 .  I wrote some helper shell scripts for now to extract / parse the compiler names since I could not figure out how to get the right output value within the .cmake file w/o doing so.  This is where the path to the mpicc is hard-coded https://github.com/sandialabs/Albany/blob/master/doc/dashboards/camobap.ca.sandia.gov/ctest_nightly_albany.cmake#L58 .  In the case of camobap, the Trilinos build does not get posted to CDash so something along the lines of what you propose could be done to get the mpicc, but it wouldn't be the case for other nightlies.  To run, you'd do "bash nightly_cron_script_albany.sh", where the relevant shell script can be found here: https://github.com/sandialabs/Albany/blob/master/doc/dashboards/camobap.ca.sandia.gov/nightly_cron_script_albany.sh .  You will need to change the paths to reflect your local machine.

**Comment by bartgol** [comment]
So, that script is for albany, and for Albany we can just get mpicc from the Trilinos install files (which we can probe from inside the ctest script). As you pointed out, that's not the case for Trilinos.

For trilinos, you must have acces to the `CMAKE_CXX_COMPILER` var, but I suspect it's buried inside `CONFIGURE_OPTIONS`. I got a bit lost in the hops of files that the script create and modify via sed/awk, but if I understand correctly, all options are eventually dumped in the `CDASH-TRILINOS-FILE.TXT` file? Tbh, I'm a bit puzzled on how the options are indeed parsed, since CONFIGURE_OPTIONS is set to  `CDASH-TRILINOS-FILE.TXT`, while I would expect something like `file(READ CDASH-TRILINOS-FILE.TXT CONFIGURE_OPTIONS)`...

Anyway,I think hard coding the compiler is fine, but for the sake of automatization, the compiler name is definitely retrievable from within the `ctest_nightly_trilinos_tmp.cmake` file.
