### ISSUE TITLE
FieldUtils class purpose?

### ISSUE THREAD

**Issue by bartgol** [sandialabs/Albany#855]
What's the point of this class? I see it used in a few places in LandIce, but it appears we can allocate some MDFields, but never use them? Can we purge it?

@jewatkins I saw your name with git blame, so hopefully you know more. Maybe it's a leftover from when you were experimenting strategies for memoization?

**Comment by jewatkins** [comment]
This is used to allocate/manage MDFields in Albany instead of phalanx to reduce memory. Basically, if we allocate the fields starting on line https://github.com/sandialabs/Albany/blob/master/src/problems/Albany_FieldUtils.cpp#L27 ourselves, phalanx won't create these fields for each evaluation type. For example, without this, `wGradBF` would be allocated more than twice for the residual, Jacobian and all other evaluation times. This is one of the things we did to get the memory footprint down so that we can run larger problems on fewer GPUs.

I'm pretty sure it's still being used. Otherwise, we wouldn't be able to run some of the performance cases on weaver (although that's been down for a while now...).

**Comment by bartgol** [comment]
I now see how the fields end up being used. I don't see how it manages to reduce the memory usage (which I suppose came from multiple field managers), but I trust you, so I can close this.
