### ISSUE TITLE
blake builds down due to Kokkos 4.0 promotion

### ISSUE THREAD

**Issue by jewatkins** [sandialabs/Albany#917]
blake build is down due to https://github.com/trilinos/Trilinos/pull/11600

`gcc 7.2.0` is the newest version that has openmpi. `intel 19.3.199` is showing up as `Compiler: Intel 19.0.0.20190206` for some reason. And when I run `mpicxx --version`, I get `19.0.3.199`...

@ikalash @mperego We should probably discuss how we want to proceed. I could probably try to get the intel build working with a newer compiler (I think we'd have to build some tpls ourselves) but we'd have to start from scratch with the gcc build (possibly with spack although I'm not sure if I'd trust the mpi build). Not sure if we'll get much support from admins, my ticket for cmake still has no response https://github.com/sandialabs/Albany/issues/914

**Comment by ikalash** [comment]
I was going to open the same issue.  I was going to suggest you try to figure out how to get the build working again with newer compilers.  Can we request that a newer gcc module get installed on blake?  If it's required for Kokkos, it will be not just us who need it.

**Comment by jewatkins** [comment]
There are newer gcc modules but there are no corresponding openmpi builds. They haven't responded to my cmake ticket so I'm not sure if they would respond to a new openmpi build. Then we also need to build all the tpls. So at that point, maybe it makes sense to just do everything with the spack build?

I could try building openmpi and test it with hello world. I'm mostly just worried that it won't work across nodes if I build it myself.

**Comment by ikalash** [comment]
How did you open the cmake ticket?  I opened one a couple days ago and they replied immediately, saying it was already installed.  I emailed ***@***.******@***.***> .

I would not try to push your own compilers/openmpi quite honestly...  the modules should be used for this when possible.  I think it's worth checking if they can accommodate.  Feel free to CC me when you email the help line.


From: Jerry Watkins ***@***.***>
Sent: Wednesday, March 8, 2023 7:52 PM
To: sandialabs/Albany ***@***.***>
Cc: Tezaur, Irina ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [sandialabs/Albany] blake builds down due to Kokkos 4.0 promotion (Issue #917)


There are newer gcc modules but there are no corresponding openmpi builds. They haven't responded to my cmake ticket so I'm not sure if they would respond to a new openmpi build. Then we also need to build all the tpls. So at that point, maybe it makes sense to just do everything with the spack build?

I could try building openmpi and test it with hello world. I'm mostly just worried that it won't work across nodes if I build it myself.

-

**Comment by ikalash** [comment]
This was supposed to say I emailed blake-help@sandia.gov .

**Comment by jewatkins** [comment]
yeah I emailed blake-help on 2/21 and cc'd you. Ah okay I see the new cmake module but they never responded to me. I'll go ahead and close my ticket an open a new one for openmpi/gcc. We would still need to build our own tpls. I'll ask about that too.

**Comment by jewatkins** [comment]
Okay I sent an email for gcc. I also try the newer intel builds again to see if issues have been fixed.

**Comment by jewatkins** [comment]
so one of the intel devpacks doesn't have parallel netcdf enabled and the other doesn't have boostlib so we'll have to build our own tpls for newer intel.

**Comment by jewatkins** [comment]
there was an issue deleting the gcc dir. blake-gcc should be up tomorrow. I haven't gotten a response for intel modules. I think we should consider getting rid of it and just use gcc.

**Comment by bartgol** [comment]
> there was an issue deleting the gcc dir. blake-gcc should be up tomorrow. I haven't gotten a response for intel modules. I think we should consider getting rid of it and just use gcc.

I am actually reluctant to abandon intel compilers on intel chips, but not enough to reject evidence: do we have any datapoint for intel-vs-gcc compiler on intel chips? My naive assumption is that intel's compiler ought to do better than a generic compiler on their own chips, but perhaps it's just an assumption (or the boost is negligible).

**Comment by jewatkins** [comment]
we have some old data showing not much of a difference but the real performance boost comes from pardiso. But the reality is, without intel support from cluster devs on this machine, we're somewhat out of luck. Unless we want to try to debug a mpi/spack build on blake.

**Comment by bartgol** [comment]
Ok. I guess we can try out GCC, and see how it goes, in terms of pass/fail and performance, and then decide. If it works better, then yes, we can switch.

**Comment by jewatkins** [comment]
blake has been working for a while now.
